INSERT INTO TB_CATEGORY (name, created_at)
VALUES
    ('Sedan', NOW()),
    ('SUV', NOW()),
    ('Hatchback', NOW()),
    ('Crossover', NOW()),
    ('Esportivo', NOW()),
    ('Utilitário', NOW()),
    ('Compacto', NOW()),
    ('Luxo', NOW()),
    ('Pickup', NOW()),
    ('Minivan', NOW()),
    ('Conversível', NOW()),
    ('Elétrico', NOW()),
    ('Esportivo de Luxo', NOW()),
    ('Subcompacto', NOW()),
    ('Cupê', NOW()),
    ('Off-Road', NOW()),
    ('Clássico', NOW()),
    ('Microcarro', NOW());
