-- Relacionamentos entre carros e categorias
INSERT INTO TB_CARS_CATEGORY (cars_id, category_id) VALUES
  (1, 1),   -- Toyota Corolla (Sedan)
  (2, 5),   -- Ford Mustang (Esportivo)
  (3, 2),   -- Honda CR-V (SUV)
  (4, 3),   -- Volkswagen Golf (Hatchback)
  (5, 9),   -- Chevrolet Silverado (Pickup)
  (6, 11),  -- Tesla Model 3 (Carro Elétrico)
  (7, 7),   -- Nissan Sentra (Compacto)
  (8, 8),   -- BMW 3 Series (Luxo)
  (9, 2),   -- Toyota RAV4 (SUV)
  (10, 9),  -- Ford F-150 (Pickup)
  (11, 2),  -- Hyundai Kona (SUV)
  (12, 8),  -- Mercedes-Benz C-Class (Luxo)
  (13, 16), -- Jeep Wrangler (Off-Road)
  (14, 5),  -- Chevrolet Camaro (Esportivo)
  (15, 2),  -- Mazda CX-5 (SUV)
  (16, 8),  -- Audi A4 (Luxo)
  (17, 4),  -- Subaru Outback (Crossover)
  (18, 7),  -- Kia Seltos (Compacto)
  (19, 5),  -- Porsche 911 (Esportivo)
  (20, 4),  -- Ford Explorer (Crossover)
  (21, 1),  -- Toyota Camry (Sedan)
  (22, 4),  -- Chevrolet Equinox (Crossover)
  (23, 7),  -- Honda Civic (Compacto)
  (24, 4),  -- Ford Escape (Crossover)
  (25, 4),  -- Nissan Rogue (Crossover)
  (26, 1),  -- Volkswagen Jetta (Sedan)
  (27, 2),  -- Jeep Grand Cherokee (SUV)
  (28, 7),  -- Hyundai Elantra (Compacto)
  (29, 9),  -- GMC Sierra (Pickup)
  (30, 2),  -- Kia Telluride (SUV)
  (31, 4),  -- Subaru Forester (Crossover)
  (32, 7),  -- Mazda3 (Compacto)
  (33, 8),  -- Lexus RX (Luxo)
  (34, 4),  -- Audi Q5 (Crossover)
  (35, 1);
