server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/carpark
    username: carpark
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
